baseurl = "https://lookatthhedata.netlify.com/"
title = "We'll Have To Look At The Data"
theme = "ghostwriter"
languageCode = "en-us"
copyright = "Alex Denvir"
disqusShortname = ""
googleAnalytics = "UA-109524941-1"

[Author]
    name = "Alex Denvir"
    profile = "https://twitter.com/eldenvo"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "We'll Have To Look At The Data"
    description = "Doing things with numbers and maps"
    github = "https://github.com/eldenvo"
    twitter = "https://twitter.com/eldenvo"
    bio = "blog biograph"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""
    
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "ir-black"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[Permalinks]
    post = "/:filename/"

[[menu.main]]
    name = "Posts"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2
